In [1]:
import torch
import torchvision.transforms as transforms
from mobilenetv3 import *

from PIL import Image
import os

In [2]:
model = mobilenetv3(mode='large', n_class=2)
state_dict = torch.load('./weights/mobilenetv3_30.pkl')
model.load_state_dict(state_dict)
model.eval()

trans = transforms.Compose([
        transforms.Resize(int(224/0.875)),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
        ])

In [3]:
def test(path_test):
    img = Image.open(path_test)
    img = trans(img)
    img = torch.unsqueeze(img, 0)
    #img = img.cuda()

    with torch.no_grad():
        out = model(img)
        #_, max_index = torch.max(out, 1)
        print(out)

In [7]:
path1 = "./valdir/pointer/000650_1.jpg"
path2 = "./valdir/pointer/000650_2.jpg"
path3 = "./valdir/greenlight/000771_4.jpg"
path4 = "./valdir/greenlight/000844_3.jpg"

In [8]:
test(path1)
test(path2)
test(path3)
test(path4)

tensor([[-6.4641,  6.1145]])
tensor([[-10.4175,   9.7521]])
tensor([[ 5.6226, -5.5151]])
tensor([[ 7.5515, -7.4701]])
